### ISSUE TITLE
404 error should not be an error screen

### ISSUE THREAD

**Issue by Oreolek** [FuzzJunket/planiverse#6]
When there is a toot and you click to get the details but the toot is already deleted you get a 404 Not Found error.

Planiverse throws a Client Error instead of a nice page.

**Comment by FuzzJunket** [comment]
I've created an error page and added some basic error handling for this scenario. I'm not 100% happy with the way the page looks and the exception handling is a bit unsophisticated for now, but I can build it out more later when I'm more certain how it should look.
